### ISSUE TITLE
*CRITICAL* auto-redirect to home page from dashboard

### ISSUE THREAD

**Issue by Citi3enKane** [worbli/website#41]
when you click dashboard whilst on homepage it only displays dash board for a few seconds and reverts back to home page.

**Comment by Citi3enKane** [comment]
![redirect](https://user-images.githubusercontent.com/40879719/48770568-bdcada80-ecf9-11e8-8706-d7868a7457ba.gif)

**Comment by tkaraivanov** [comment]
I noticed this happens only if the user has already submitted an application. In this situation, the Application tab in the sidebar is disabled, and the Dashboard link leads to it. So to fix this problem, we need the Dashboard button to lead to the first non-disabled tab in the sidebar - it would be Status in this case. Alternatively, we can always have the Application tab available, but display a different page if the application has already been submitted. This goes in line with what we discussed earlier - it should be a "contact support if you need to resubmit your application" page if the application has gone through and failed.
