### ISSUE TITLE
ADD tracking code for AUTOPILOT

### ISSUE THREAD

**Issue by Citi3enKane** [worbli/website#45]
Message from Chethan:.. @Peregrine - Do not forget to add Autopilot tracking code to portal yeah!
Peregrine [10:31]
when does that need to be added
?
Chethan [10:32]
Before it goes live. It's just code snippets to header.

**Comment by Citi3enKane** [comment]
[Autopilot - Tracking Code for Portal.docx](https://github.com/worbli/portalFrontEnd/files/2602427/Autopilot.-.Tracking.Code.for.Portal.docx)

**Comment by bkawk** [comment]
I have added this before and it has stopped/blocked the page from rendering, the result is an annoying bottom bar, with something about accepting cookies (which we don't use) that the user is forced to accept, if we need this lets build it ourselves
