### ISSUE TITLE
Still says "saving"

### ISSUE THREAD

**Issue by Sxandon** [worbli/website#47]
When testing the portal I got to the profile creation page. After doing the Onfido step - I returned to the page clicked the blue button at the bottom and it has said Saving for the last 45 minutes... Not sure what's supposed to happen next.
<img width="1056" alt="screen shot 2018-11-20 at 11 27 20 pm" src="https://user-images.githubusercontent.com/45225491/48825680-ffb94800-ed1c-11e8-9ecd-2199bbd5d8fa.png">

**Comment by tkaraivanov** [comment]
This should be resolved. Can you check again?
