### ISSUE TITLE
Explanation text on the Worbli account creation page

### ISSUE THREAD

**Issue by tkaraivanov** [worbli/website#55]
We need to put the following explanation text on the Account page in the view where they are creating a new Worbli account:

`Choose your desired Worbli account name (6-12 characters, must start with a letter and can only contain letters and numbers 1-5).
Note: high profile trademarked names such as "google", "facebook", etc. are not allowed and accounts that have chosen such names will be frozen.`

**Comment by bkawk** [comment]
![Screenshot 2018-11-30 at 08.36.42.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/56e969973a5bda1300faf627/125516c66e82c728ace21e0d46db978826878dba87e6ab03f60da1cc6417763e7a54e32a64c5b370f1112d4f5b5d5cb053181d1ba6acda6fb4bc2e75d80a5fe9d7385e77c13e15a8ea821eb801ec20d94880b6ae965e82b96371b8d6d6056b5c17129bfe5a3fa19c4fcb5df543e34f57a6133f71ab.png)
