### ISSUE TITLE
Profile always saving

### ISSUE THREAD

**Issue by bkawk** [worbli/website#56]
on the /dashboard/profile route, if you don’t enter any data and hit save  it will show you the fields you need to complete, if you then complete only those ones, and hit save, nothing happens and the user is stuck till a refresh happens

**Comment by bkawk** [comment]
I propose we cut the dorm back to just the fields we need
![Screenshot 2018-12-03 at 14.10.40.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/56e969973a5bda1300faf627/125516c66e82c728ace21e0d46db978826878dba87e6ab03f60da1cc6417753e7957e32a64c5b27cf1132b4f5b5f5cb053181d1ba6acda6fb4bc2e75d80a5fe9d7385e77c13e15a8ea821eb801ec20d94880b6ae965e82b96371b8d6d6056b5c17129bfd5d3fa19c4fcb50f74ce54a54a5133671ab.png)

**Comment by tkaraivanov** [comment]
Yes, I agree, let's go with your simplified address fields

**Comment by bkawk** [comment]
Comments from Daqian...
The only thing I would change is this: instead of just say State, make it
State/Province

Also, I am not sure if the Chinese provinces (such as Zhejiang Province) are available in scroll down menu. If not, then I suggest make this a blank field for them to write their province down.

One more caution is that, I need to confirm with Onfido with the name field thing. As you are aware that Chinese name is Last name, First name. If we put Full Name like above, I am concerned that people would just put their names according to their tradition. It will again create a mess in the Onfido System. For this reason, I suggest let's keep First name, and Last Name options available as before.
