### ISSUE TITLE
Replace slide images with newer version & FAQ illustration 

### ISSUE THREAD

**Issue by Citi3enKane** [worbli/website#6]
![bp stage-12](https://user-images.githubusercontent.com/40879719/47263661-83bebb00-d538-11e8-8d99-750c9f302815.jpg)
![worbli ads-01](https://user-images.githubusercontent.com/40879719/47263662-83bebb00-d538-11e8-9930-c00302f791db.jpg)
![worbli ads-02](https://user-images.githubusercontent.com/40879719/47263663-84575180-d538-11e8-970d-819ff4d1f004.jpg)
![worbli ads-03](https://user-images.githubusercontent.com/40879719/47263664-84575180-d538-11e8-89d0-3a1007dc843d.jpg)
![worbli ads-04](https://user-images.githubusercontent.com/40879719/47263665-84575180-d538-11e8-89b5-25b534c69f4b.jpg)

**Comment by bkawk** [comment]
I have learnt today that these are to updated again, please let me know when they are ready
