### ISSUE TITLE
Onfido complete message

### ISSUE THREAD

**Issue by bkawk** [worbli/website#61]
When I  finished the onfido part of the process it displayed 'Verification Complete' 'Thank you' with no indication what to do next.

**Comment by bkawk** [comment]
In the past we have used the below code to change the text in the web SDK, how do we change the text in the final screen?
```
phrases: {welcome: {
    title: 'Upload your documents',
    description_p_1: "Once you are done here, close this tab & return to your application",
        description_p_2: "If your first ID doesn't work. Please upload another ID.",
            next_button: "Select Documents"
            }},
```

**Comment by tkaraivanov** [comment]
duplicate #76
