### ISSUE TITLE
Simplify address fields

### ISSUE THREAD

**Issue by bkawk** [worbli/website#62]
the form is still a bit confusing with all the fields for apartment/flat number, build name, etc.

**Comment by Citi3enKane** [comment]
![image](https://user-images.githubusercontent.com/40879719/49266745-4849d180-f492-11e8-82d9-e4cf218a94b2.png)

**Comment by bkawk** [comment]
This article gives lots of good advice https://baymard.com/blog/address-line-2 even though onfido doesn't need the address anymore I guess we as a company still need to collect the address. Indicating the mandatory fields should also be part of the upgrade

**Comment by tkaraivanov** [comment]
Will be fixed in #56
