### ISSUE TITLE
Whale account redirect, to a new VIP form fill in page

### ISSUE THREAD

**Issue by Citi3enKane** [worbli/website#8]
**Add a referral link into verify email address - email**

The user is redirected to a “success page” and is presented with a form to complete which is embedded to the portal page with 3 sections (multiple choice Qs with checkboxes). At the top of this page is a short paragraph from Domenic thomas (CEO)

“Dear Worbli User. Because you're receiving a large amount of WBI from our Sharedrop, we want to invite you to attend an exclusive seminar and AMA with me and our team. We also want to invite you to learn more about what were building, and what you would like to see built on WORBLI that will benefit you.

This form upon completion is emailed to Sean/John to review and follow up.
Section 1: Exclusive educational seminar (RSVP... YES / NO / Maybe - please still send me the invite)

Section 2: dApp Menu (Tick which dApp you are interested in learning more about or supporting. Select as many as you want. There must be a “None of the above” option there too

Section 3: what dApps would you like to see built on WORBLI? (Textbox for user to complete)

Section 4: I want to verify my account to claim my sharedrop (YES / NO / Undecided)

CALL TO ACTION BUTTON = Submit

After completing this form:
If the user answered NO to any of the questions we must be careful how to respond.
Surveys should be reviewed and planned accordingly.

Summary - the user will receive an email from Domenic and Sean as per below.
*This is an exclusive user journey for accounts with more than 200,000 EOS.

**Comment by tkaraivanov** [comment]
Perhaps we should add a section:
Section 5: This account is an exchange account holding tokens on behalf of other users (YES/NO)

**Comment by Citi3enKane** [comment]
Good point. I will add it as another issue top priority,  hope we get to it in time.Thanks,                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: tkaraivanovSent: Friday, 26 October, 2018 8:02 PMTo: worbli/PortalFrontEndReply To: worbli/PortalFrontEndCc: Citi3enKane; AuthorSubject: Re: [worbli/PortalFrontEnd] Whale account redirect, to a new VIP form fill in page (#8)Perhaps we should add a section:
Section 5: This account is an exchange account holding tokens on behalf of other users (YES/NO)

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/worbli/PortalFrontEnd","title":"worbli/PortalFrontEnd","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/worbli/PortalFrontEnd"}},"updates":{"snippets":[{"icon":"PERSON","message":"@tkaraivanov in #8: Perhaps we should add a section:\r\nSection 5: This account is an exchange account holding tokens on behalf of other users (YES/NO)"}],"action":{"name":"View Issue","url":"https://github.com/worbli/PortalFrontEnd/issues/8#issuecomment-433384936"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/worbli/PortalFrontEnd/issues/8#issuecomment-433384936",
"url": "https://github.com/worbli/PortalFrontEnd/issues/8#issuecomment-433384936",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [worbli/PortalFrontEnd] Whale account redirect, to a new VIP form fill in page (#8)",
"sections": [
{
"text": "",
"activityTitle": "**tkaraivanov**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@tkaraivanov",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"worbli/PortalFrontEnd\",\n\"issueId\": 8,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"worbli/PortalFrontEnd\",\n\"issueId\": 8\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/worbli/PortalFrontEnd/issues/8#issuecomment-433384936"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 399066826\n}"
}
],
"themeColor": "26292E"
}
]
